os:
  - linux
  - osx
language: csharp
solution: QuickFont.sln
before_script:
  - mono .paket/paket.bootstrapper.exe
  - mono .paket/paket.exe restore
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e76a9d672eaa46d01c20
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
